# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
 - release 
 - devel
sudo: required
r_check_args: "--as-cran --no-build-vignettes --ignore-vignettes"
cache: packages
warnings_are_errors: true
r_github_packages:
  - kkholst/mets